algo = input('Digite algo: ')
print(f'O tipo primitivo dessa string é {type(algo)}')
print(f'O que você digitou é Número: {algo.isnumeric()}')
print(f'O que você digitou é uma String: {algo.isalpha()}')
print(f'O que você digitou é Numéro ou uma String: {algo.isalnum()}')
print(f'O que você digitou está em maisculo: {algo.isupper()}')
print(f'O que você digitou está em minúsculo: {algo.islower()}')
print(f'O que você digitou somente tem espaços: {algo.isspace()}')
print(f'O que você digitou está capitalizada: {algo.istitle()}')